### ISSUE TITLE
Chrome vs Android in ARA

### ISSUE THREAD

**Issue by dmdabbs** [privacysandbox/attestation#7]
For registration purposes is use of `Attribution-Reporting-Register-OS-Source` considered a Chrome API or an Android use?

**Comment by ailadas** [comment]
> เพื่อวัตถุประสงค์ในการลงทะเบียน การใช้งาน`Attribution-Reporting-Register-OS-Source`Chrome API ถือว่าเป็นการใช้ Android หรือไม่

**Comment by GeorgiaFranklin** [comment]
An entity using Attribution-Reporting-Register-OS-Source is using Chrome API (i.e. it is considered a Chrome API use). Additionally, it is considered an Android API use if the entity is using Attribution-Reporting-Register-OS-Source in order to delegate to Android.  If the tester intends for their registrations to be delegated to Android, they must enroll for Android as well.

**Comment by dmdabbs** [comment]
Thank you for verifying.
